### PR TITLE
docker -> moby

### PR DESCRIPTION
**Pull request by ehazlett**
This updates the gordon bot to use the new `moby/moby` repo.

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 👼

**Comment by jiangbingo** [comment]
sad to get it in the news .

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
> sad to get it in the news .

@jiangbingo nothing to be sad about; it's all still open source, and with the split between the Moby _project_ and Docker _product_, the foundations can be even more open than before

**Pull request merged**
